"""System templates and instances for simulation components.

A lightweight SystemTemplate describes a type of system (e.g., a population,
an electrical grid). `SystemTemplate.instantiate()` creates a `SystemInstance`
which can hold runtime state. Instances are small, hashable identifiers that
can be attached to `Event` objects.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, Optional


@dataclass
class SystemTemplate:
    name: str
    properties: Dict[str, Any] = field(default_factory=dict)

    def instantiate(self, instance_id: Optional[str] = None, **state) -> "SystemInstance":
        """Create a SystemInstance from this template.

        If `instance_id` is omitted, a simple id based on the template name
        and an internal counter will be generated by the caller. Caller can
        provide arbitrary initial `state` fields.
        """
        return SystemInstance(template=self, id=instance_id or f"{self.name}-inst", state=dict(state))


@dataclass
class SystemInstance:
    template: SystemTemplate
    id: str
    state: Dict[str, Any] = field(default_factory=dict)

    def __repr__(self) -> str:  # pragma: no cover - trivial
        return f"SystemInstance(id={self.id!r}, template={self.template.name!r})"

    def __hash__(self) -> int:
        return hash((self.template.name, self.id))

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, SystemInstance):
            return False
        return (self.template.name, self.id) == (other.template.name, other.id)
